#!/usr/bin/env python3
"""
Script to create a success file with current date and list directory contents.
"""

import os
from datetime import datetime

def create_success_file():
    """Create framework_test_success.txt with current date and success message."""
    
    # Get current date
    current_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Format the message string
    message = f"Framework test successful! Date: {current_date}\\nGenerated by automated script."
    
    # File path
    file_path = 'framework_test_success.txt'
    
    # Open file in write mode and write message
    with open(file_path, 'w') as file:
        file.write(message)
    
    print(f"Successfully created file: {file_path}")
    print(f"Message written: {message}")
    
    # List directory contents to confirm file existence
    print("\nListing directory contents:")
    files = os.listdir('.')
    for file_name in files:
        if file_name == 'framework_test_success.txt':
            print(f"✓ {file_name} - FOUND")
        else:
            print(f"  {file_name}")
    
    return file_path

if __name__ == "__main__":
    created_file = create_success_file()
    print(f"\nScript completed. File '{created_file}' has been successfully created.")